"""New Migration

Revision ID: baa9097006be
Revises: 
Create Date: 2023-01-01 18:24:48.148114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa9097006be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sneaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('free_delivery', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sneaker_brand_name'), 'sneaker', ['brand_name'], unique=False)
    op.create_index(op.f('ix_sneaker_color'), 'sneaker', ['color'], unique=False)
    op.create_index(op.f('ix_sneaker_description'), 'sneaker', ['description'], unique=False)
    op.create_index(op.f('ix_sneaker_free_delivery'), 'sneaker', ['free_delivery'], unique=False)
    op.create_index(op.f('ix_sneaker_name'), 'sneaker', ['name'], unique=False)
    op.create_index(op.f('ix_sneaker_size'), 'sneaker', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sneaker_size'), table_name='sneaker')
    op.drop_index(op.f('ix_sneaker_name'), table_name='sneaker')
    op.drop_index(op.f('ix_sneaker_free_delivery'), table_name='sneaker')
    op.drop_index(op.f('ix_sneaker_description'), table_name='sneaker')
    op.drop_index(op.f('ix_sneaker_color'), table_name='sneaker')
    op.drop_index(op.f('ix_sneaker_brand_name'), table_name='sneaker')
    op.drop_table('sneaker')
    # ### end Alembic commands ###
